name: smartroad
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Video player
  video_player: ^2.8.3

  # Permissions
  permission_handler: ^11.0.0

  # Base de données et utilitaires
  path: ^1.8.3
  crypto: ^3.0.3
  bcrypt: ^1.2.0          # Pour le hash des mots de passe
  mongo_dart: ^0.10.3      # Connexion à MongoDB Atlas

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.2.2

  # Localisation et géolocalisation
  geolocator: ^10.0.0
  # location retiré (non utilisé) — évite MissingPluginException flutter_background_fetch

  # Google Maps
  google_maps_flutter: ^2.5.0

  # API calls
  dio: ^5.3.0
  http: ^1.1.0
  cloudinary_public: ^0.21.0

  # Animation et UI
  lottie: ^3.0.1

  # Navigation
  go_router: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/images/logo_treg_eslama.png
    - assets/animations/